baseURL = 'https://sunkz.top/'
languageCode = 'en-us'
title = 'Sunkz'
theme = 'paper'
publishdir = 'docs'

[menu]
  [[menu.main]]
    identifier = "主页"
    name = "主页"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "文本工具箱"
    name = "文本工具箱"
    url = "/pages/tools.html"
    weight = 20
  [[menu.main]]
    identifier = "CCBot"
    name = "CCBot"
    url = "/pages/cc-bot.html"
    weight = 30
  [[menu.main]]
    identifier = "关于我"
    name = "关于我"
    url = "/about/"
    weight = 40

[params]
    color = 'light'
    github = 'sunkz'
