baseURL = 'https://sunkz.top/'
languageCode = 'en-us'
title = 'Sunkz'
theme = 'paper'
publishdir = 'docs'

[menu]
  [[menu.main]]
    identifier = "主页"
    name = "主页"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "工具集"
    name = "工具集"
    url = "/tools/"
    weight = 10
  [[menu.main]]
      identifier = "关于我"
      name = "关于我"
      url = "/about/"
      weight = 10

[params]
    color = 'light'
    github = 'sunkz'
